export const inventories = [
  {
    item_id: 1,
    ministry_id: 1,
    item_name: "Water Filter",
    quantity: 50,
    description: "High-efficiency water filter for rural areas.",
  },
  {
    item_id: 2,
    ministry_id: 2,
    item_name: "Rainwater Harvesting Kit",
    quantity: 30,
    description: "Kit for setting up rainwater harvesting systems.",
  },
  {
    item_id: 3,
    ministry_id: 1,
    item_name: "River Cleaning Equipment",
    quantity: 20,
    description: "Equipment for cleaning polluted rivers.",
  },
  {
    item_id: 4,
    ministry_id: 2,
    item_name: "Solar Panels",
    quantity: 100,
    description: "Solar panels for installation in government buildings.",
  },
  {
    item_id: 5,
    ministry_id: 2,
    item_name: "Power Cables",
    quantity: 200,
    description: "High-voltage power cables for grid maintenance.",
  },
  {
    item_id: 6,
    ministry_id: 2,
    item_name: "Transformers",
    quantity: 10,
    description: "Transformers for power grid upgrades.",
  },
  {
    item_id: 7,
    ministry_id: 3,
    item_name: "Street Lights",
    quantity: 150,
    description: "LED street lights for urban and rural roadways.",
  },
  {
    item_id: 8,
    ministry_id: 3,
    item_name: "Traffic Signals",
    quantity: 25,
    description: "Traffic signals for busy intersections.",
  },
  {
    item_id: 9,
    ministry_id: 3,
    item_name: "Road Barriers",
    quantity: 75,
    description: "Barriers for road construction and maintenance zones.",
  },
];
